---
# tasks file for postgres
- name: "Ensure PostgreSQL packages are installed."
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "postgresql"
      - "postgresql-server"
      - "postgresql-contrib"
      - "postgresql-libs"
      - "python-psycopg2"
      - "python-ipaddress"
    state: present
    update_cache: true

- name: "check init postgres"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: "postgres_data"

- name: "init postgres"
  ansible.builtin.shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "start and enable service"
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: "create database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become_user: postgres

- name: "create database user"
  become_user: postgres
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER

- name: "grap permissions for db user to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become_user: postgres

- name: "allow md5 connection"
  postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: all
    address: 127.0.0.1/32
    method: md5
    users: "{{ db_user }}"
    create: true
  become_user: postgres

- name: "restart postgres"
  service:
    name: postgresql
    state: restarted
